### PR TITLE
Move diff bar to the right of the line numbers (like in the GitSCC extension) Fixes #71

### LINKED ISSUE #71: Move diff bar to the right of the line numbers
The git Source Control Provider extension shows the diff bar right of the document changes bar, with is right of line numbers. Can GitDiffMargin do the same? I have line numbers enabled everywhere by default because it helps a lot when debugging or reading compile errors or other messages. Now I have two colour bars far away from each other. It would be nice if they were close to each other, preferably in the order that the old GitSCC extension (which is no longer available for VS 2015) uses.

### PR DESCRIPTION
**Pull request by dg9ngf**

### CODE REVIEW

**Comment by sharwell** [comment]
I agree with this change, in particular for the following reasons:

* It makes sense for this bar to be near the existing track changes margin
* Due to the way user input works, it's essential for the track change margin to be next to the line numbers (both are used for selecting whole lines)
* The track changes margin indicator and git diff margin indicator in the scroll bar use the same relative order we are discussing here
* The "removed" indicator seems to make particular sense appearing near the text

:bulb: The summary text for this pull request (right at the top of this page, not in the commit itself) should include the text "Fixes #71" so GitHub knows to associate the pull request with the issue.

**Comment by laurentkempe** [comment]
:+1: Thanks

**Comment by dg9ngf** [comment]
It'd be great if one could install this through the official gallery and not need to build a current version of it myself. :-)

**Comment by sharwell** [comment]
@dg9ngf :confused: I did install it from the gallery. What version of Visual Studio are you using, and what error are you seeing?

**Comment by sharwell** [comment]
@dg9ngf Ignore my previous comment. I thought you commented on #79. :no_mouth:

**Comment by dg9ngf** [comment]
I didn't even know there was a problem in general, I'm using this self-built version for a few months in VS 2015 RC and RTM. I just wish for a release that includes this change.

**Comment by sharwell** [comment]
Me too :+1: 

@laurentkempe You on board for a 3.1? It'll increase your download count on the gallery. :wink:

**Comment by sharwell** [comment]
@dg9ngf I just realized the VSIX is getting attached as an [AppVeyor artifact](https://ci.appveyor.com/project/laurentkempe/gitdiffmargin/build/3.0.0.6/artifacts). If you click the [Build status](https://ci.appveyor.com/project/laurentkempe/gitdiffmargin) link on the main page you can always download the latest and greatest. :+1: 

But yes the gallery would still be even easier. :smile:

**Comment by laurentkempe** [comment]
@dg9ngf I was thinking to have your change included when I would implement some others improvements, but didn't had the time till now. I understand your frustration, so I will create a new version as proposed by @sharwell

**Pull request merged**
