### PR TITLE
updated manifest for visual studio 15 (visual studio 2016 preview)

### PR DESCRIPTION
**Pull request by heinzbeinz**
I also updated the nuget package for libgit2sharp (0.23 is only available as preview)

### CODE REVIEW

**Comment by laurentkempe** [comment]
Thanks @heinzbeinz I guess you have tested it with Visual Studio 2016 preview?

**Comment by laurentkempe** [comment]
I still need to verify that the LibGit2Sharp build version 0.23.0-pre20150419160303 contains the memory leak fixed in the version I manually setup in GitDiffMargin v3.1.2

**Comment by heinzbeinz** [comment]
Yes, I have tested it. I really missed your great extension in visual studio preview.

**Comment by laurentkempe** [comment]
Thanks @heinzbeinz for the PR I have worked the whole day without any issue with it so I will release it!

**Pull request merged**
